### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by Hectorstar** [mlwong/HAMeRS#18]
Hi mlwong
I found a few bugs when using HAMeRS
(1)boundary conditions
when using boundary conditions in 2D:
 boundary_edge_xhi {
   boundary condition=ADIABATIC_NO_SLIP
 } 
 boundary_edge_yhi {
   boundary condition=ADIABATIC_NO_SLIP
 } 
boundary_node_xhi_yhi{
 boundary condition=XADIABATIC_NO_SLIP
 or
 boundary condition=YADIABATIC_NO_SLIP
}
there will some bugs in boundary_node_xhi_yhi.
(2)when the partitioner_type=TreeLoadBalancer in main.C. An error occurs when running 120 cores to 300,000 steps in BalanceBoxBreaker.C :ideal_load_break>0,

**Comment by Hectorstar** [comment]
I have fixed the boundary conditions, turn off the TBOX_ERROR in BasicCartesianBoundaryUtilities2.cpp at ret_edge==-1

**Comment by mlwong** [comment]
Thanks for looking into (1). I will fix it as soon as possible in the code.

As for bug (2), I think the TreeLoadBalancer in SAMRAI library has a bug and I have also experience the same error before (also confirmed with developer of SAMRAI library). Would you mind setting `partitioner_type = "CascadePartitioner"` explicitly in the section `Main` of your input file? I will change the default partitioner/balancer to be CascadePartitioner in HAMeRS as soon as possible too.
