### ISSUE TITLE
BOOST_CAST ERROR

### ISSUE THREAD

**Issue by YinLiu-91** [mlwong/HAMeRS#23]
@mlwong   Hello,when I build  this code,there are a lot of errors just like"use of undeclared identifier 'BOOST_CAST"。But I  include BOOST headers correctly,do you know this problem? And My boost version is 1.71.

**Comment by mlwong** [comment]
@YinLiu-91  Hi, I have never tried with boost 1.71 before. I have been using with boost 1.60/1.61 for a long time and didn't encounter the problem mentioned.

P.S. In long term we would get rid of boost library like SAMRAI.

**Comment by mlwong** [comment]
You can now try -DHAMERS_USE_BOOST=OFF during the CMake configuration of HAMeRS and use it with the latest version of SAMRAI that also doesn't need the Boost library anymore.
